# Generated by Django 4.2.7 on 2023-11-28 07:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Товары'},
        ),
        migrations.AddField(
            model_name='article',
            name='purchase_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на покупку'),
        ),
        migrations.AddField(
            model_name='article',
            name='rating',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='article',
            name='review',
            field=models.TextField(blank=True, null=True, verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='article',
            name='full_text',
            field=models.TextField(verbose_name='Полный текст'),
        ),
    ]
