# Generated by Django 4.2.7 on 2023-11-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_alter_article_options_article_purchase_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles_images/', verbose_name='Фотография товара'),
        ),
    ]
