# Generated by Django 4.2.7 on 2023-11-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='description',
        ),
        migrations.AlterField(
            model_name='article',
            name='full_text',
            field=models.TextField(verbose_name='Полное описание'),
        ),
    ]
